<a href="https://colab.research.google.com/github/tiago-luisi/Mathematics-Statistics-DS-AI/blob/main/DSA_MAT_Exercicio6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='white'>Data Science Academy</font>
## <font color='white'>Matemática e Estatística Aplicada Para Data Science, Machine Learning e IA</font>
## <font color='white'>Lista de Exercícios 6</font>
## <font color='white'>Operações com Matrizes e Programação Python</font>

### Instalando e Carregando Pacotes

In [ ]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark.
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
!pip install -q -U watermark

In [ ]:
# Imports
import numpy as np

In [ ]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy



**Resolva os exercícios abaixo usando Linguagem Python. Faça pesquisa complementar se necessário.**

In [ ]:
# Criando duas matrizes de exemplo
matriz1 = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]
matriz2 = [[5, 2, 8], [3, 1, 2], [7, 0, 2]]

In [ ]:
print(matriz1)

[[1, 2, 3], [0, 1, 4], [5, 6, 0]]


In [ ]:
print(matriz2)

[[5, 2, 8], [3, 1, 2], [7, 0, 2]]


###  Exercício 1: Soma de Matrizes

Escreva um programa em Python que soma duas matrizes de mesmo tamanho. As matrizes devem ser lidas como listas de listas e o resultado deve ser exibido na tela. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

In [ ]:
# Com NumPy - Versão 1 (mais simples de todas)
def dsa_soma_matrizes_v1(m1, m2):
    return np.array(m1) + np.array(m2)

In [ ]:
dsa_soma_matrizes_v1(matriz1, matriz2)

array([[ 6,  4, 11],
       [ 3,  2,  6],
       [12,  6,  2]])

In [ ]:
# Com NumPy - Versão 2
def dsa_soma_matrizes_v2(A, B):

    A_np = np.array(A)
    B_np = np.array(B)

    return A_np + B_np

In [ ]:
dsa_soma_matrizes_v2(matriz1, matriz2)

array([[ 6,  4, 11],
       [ 3,  2,  6],
       [12,  6,  2]])

In [ ]:
# Sem NumPy - Versão 3
def dsa_soma_matrizes_v3(m1, m2):

    # Verifica se as matrizes têm o mesmo número de linhas e colunas
    if len(m1) != len(m2) or len(m1[0]) != len(m2[0]):

        # Retorna uma mensagem de erro se as matrizes não tiverem o mesmo tamanho
        return "As matrizes devem ter o mesmo tamanho"

    # Inicializa a matriz de resultado como uma lista vazia
    resultado = []

    # Loop através de cada linha da matriz
    for i in range(len(m1)):

        # Inicializa uma nova linha para a matriz de resultado
        linha = []

        # Loop através de cada coluna da linha atual
        for j in range(len(m1[0])):

            # Soma os elementos correspondentes das duas matrizes e adiciona à linha
            linha.append(m1[i][j] + m2[i][j])

        # Adiciona a linha recém-calculada à matriz de resultado
        resultado.append(linha)

    # Retorna a matriz de resultado após somar todos os elementos
    return resultado

In [ ]:
dsa_soma_matrizes_v3(matriz1, matriz2)

[[6, 4, 11], [3, 2, 6], [12, 6, 2]]

In [ ]:
# Sem NumPy - Versão 4 (mais complexa)
def dsa_soma_matrizes_v4(A, B):

    if len(A) != len(B) or len(A[0]) != len(B[0]):

        return "Matrizes de tamanhos diferentes"

    return [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

In [ ]:
dsa_soma_matrizes_v4(matriz1, matriz2)

[[6, 4, 11], [3, 2, 6], [12, 6, 2]]

### Exercício 2: Multiplicação de Matrizes

Implemente uma função em Python que multiplica duas matrizes. Verifique se as dimensões das matrizes são compatíveis para a multiplicação e retorne a matriz resultante. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

In [ ]:
# Sem NumPy - Versão 1 (mais complexa)
def dsa_multiplica_matrizes_v1(A, B):

    if len(A[0]) != len(B):

        return "Matrizes com dimensões incompatíveis para multiplicação"

    return [[sum(A[i][k] * B[k][j] for k in range(len(B))) for j in range(len(B[0]))] for i in range(len(A))]

In [ ]:
dsa_multiplica_matrizes_v1(matriz1, matriz2)

[[32, 4, 18], [31, 1, 10], [43, 16, 52]]

In [ ]:
# Sem NumPy - Versão 2
def dsa_multiplica_matrizes_v2(m1, m2):

    if len(m1[0]) != len(m2):

        return "As matrizes não são compatíveis para a multiplicação"

    resultado = []

    for i in range(len(m1)):

        linha = []

        for j in range(len(m2[0])):

            soma = 0

            for k in range(len(m2)):

                soma += m1[i][k] * m2[k][j]

            linha.append(soma)

        resultado.append(linha)

    return resultado

In [ ]:
dsa_multiplica_matrizes_v2(matriz1, matriz2)

[[32, 4, 18], [31, 1, 10], [43, 16, 52]]

In [ ]:
# Com NumPy - Versão 3
def dsa_multiplica_matrizes_v3(A, B):

    A_np = np.array(A)
    B_np = np.array(B)

    return np.dot(A_np, B_np)

In [ ]:
dsa_multiplica_matrizes_v3(matriz1, matriz2)

array([[32,  4, 18],
       [31,  1, 10],
       [43, 16, 52]])

In [ ]:
# Com NumPy - Versão 4 (mais simples)
def dsa_multiplica_matrizes_v4(m1, m2):
    return np.dot(m1, m2)

In [ ]:
dsa_multiplica_matrizes_v4(matriz1, matriz2)

array([[32,  4, 18],
       [31,  1, 10],
       [43, 16, 52]])

### Exercício 3: Transposição de Matriz

Crie um programa que calcula a transposta de uma matriz. A matriz deve ser inserida pelo usuário e o programa deve exibir a matriz transposta. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

In [ ]:
print(np.array(matriz1))

[[1 2 3]
 [0 1 4]
 [5 6 0]]


In [ ]:
# Com NumPy
def dsa_transposicao_v1(matriz):
    return np.transpose(matriz)

In [ ]:
dsa_transposicao_v1(matriz1)

array([[1, 0, 5],
       [2, 1, 6],
       [3, 4, 0]])

In [ ]:
# Sem NumPy
def dsa_transposicao_v2(matriz):

    return [[matriz[j][i] for j in range(len(matriz))] for i in range(len(matriz[0]))]

In [ ]:
dsa_transposicao_v2(matriz1)

[[1, 0, 5], [2, 1, 6], [3, 4, 0]]

### Exercício 4: Traço de uma Matriz

Desenvolva um script em Python que calcula o traço de uma matriz (soma dos elementos da diagonal principal). O programa deve funcionar para matrizes quadradas de qualquer tamanho. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

O traço de uma matriz é a soma dos elementos da diagonal principal da matriz.

In [ ]:
print(np.array(matriz2))

[[5 2 8]
 [3 1 2]
 [7 0 2]]


In [ ]:
len(matriz2)

3

In [ ]:
# Com NumPy - Versão 1
def dsa_traco_matriz_v1(matriz):
    return np.trace(matriz)

In [ ]:
dsa_traco_matriz_v1(matriz2)

8

In [ ]:
# Sem NumPy - Versão 2 (usando generator expression ou expressão geradora)
# As expressões geradoras são semelhantes a list comprehensions, mas em vez de criar uma lista completa
# na memória, elas geram os itens um por um, o que é mais eficiente em termos de memória.
def dsa_traco_matriz_v2(matriz):

    if len(matriz) != len(matriz[0]):

        return "A matriz deve ser quadrada"

    soma = sum(matriz[i][i] for i in range(len(matriz)))

    return soma

In [ ]:
dsa_traco_matriz_v2(matriz2)

8

In [ ]:
# Sem NumPy - Versão 3 (usando apenas loop for)
def dsa_traco_matriz_v3(matriz):

    if len(matriz) != len(matriz[0]):

        return "A matriz deve ser quadrada"

    soma = 0

    for i in range(len(matriz)):

        print("Valor do Elemento na Posição", i, i, ":", matriz[i][i])

        soma += matriz[i][i]

    return soma

In [ ]:
dsa_traco_matriz_v3(matriz2)

Valor do Elemento na Posição 0 0 : 5
Valor do Elemento na Posição 1 1 : 1
Valor do Elemento na Posição 2 2 : 2


8

### Exercício 5: Determinante de uma Matriz (Desafio)

Escreva uma função que calcula o determinante de uma matriz quadrada. Utilize a recursividade ou o método de Laplace para calcular o determinante. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

O determinante de uma matriz é um valor escalar que fornece informações importantes sobre a matriz. Ele é aplicável apenas a matrizes quadradas (matrizes com o mesmo número de linhas e colunas). O determinante tem várias interpretações e aplicações na matemática, particularmente em álgebra linear, análise e geometria.

Algumas das principais propriedades e interpretações do determinante são:

**Interpretação Geométrica**: Para matrizes 2x2 e 3x3, o determinante pode ser interpretado como a área (para matrizes 2x2) ou o volume (para matrizes 3x3) do paralelogramo ou paralelepípedo formado pelos vetores que compõem as linhas ou colunas da matriz.

**Singularidade**: Um determinante igual a zero indica que a matriz é singular (não invertível). Isso acontece quando as linhas ou colunas da matriz são linearmente dependentes, ou seja, uma linha ou coluna pode ser expressa como uma combinação linear das outras.

**Transformações Lineares**: Em termos de transformações lineares, o determinante de uma matriz que representa uma transformação linear indica se a transformação preserva, inverte ou deforma o espaço. Um determinante negativo indica que a orientação foi invertida.

**Solução de Sistemas Lineares**: O determinante é usado na regra de Cramer para resolver sistemas de equações lineares. Se o determinante da matriz dos coeficientes for diferente de zero, existe uma única solução para o sistema.

In [ ]:
# Com NumPy - Versão 1
def dsa_determinante_v1(matriz):
    return np.linalg.det(matriz)

In [ ]:
dsa_determinante_v1(matriz1)

0.9999999999999987

In [ ]:
# Sem NumPy - Versão 2 (usando expansão de Laplace)
def dsa_determinante_v2(matriz):

    """
    Calcula o determinante de uma matriz quadrada usando a expansão de Laplace.

    Args:
    matriz (list of list of int/float): Matriz quadrada para a qual o determinante será calculado.

    Returns:
    int/float: Determinante da matriz.
    """

    # Verifica se a matriz é quadrada (número de linhas igual ao número de colunas)
    if len(matriz) != len(matriz[0]):
        return "A matriz deve ser quadrada"

    # Caso base para uma matriz 1x1
    if len(matriz) == 1:
        return matriz[0][0]

    # Caso base para uma matriz 2x2
    if len(matriz) == 2:
        return matriz[0][0] * matriz[1][1] - matriz[0][1] * matriz[1][0]

    # Inicializa o determinante como 0
    det = 0

    # Loop sobre os elementos da primeira linha
    for c in range(len(matriz)):

        # Cria uma submatriz removendo a linha atual e a coluna c
        submatriz = [linha[:c] + linha[c+1:] for linha in matriz[1:]]

        # Adiciona ao determinante o valor do elemento atual multiplicado pelo determinante
        # da submatriz, ajustado pelo sinal (-1)^c
        det += ((-1) ** c) * matriz[0][c] * dsa_determinante_v2(submatriz)
        #det += ((-1) ** c) * matriz[0][c] * dsa_determinante_v1(submatriz)

    return det

In [ ]:
dsa_determinante_v2(matriz1)

1

In [ ]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy



In [ ]:
#%watermark -v -m

In [ ]:
#%watermark --iversions

# Fim